#cluster settings

# cluster size
numberofnodes: 2
#cluster name, bid's and tasks will use it
tag: "TEST"
# Task estimated time of arrival, sec
eta: 180
# Template for task yaml
template_file: "claymore.yaml"
#template_file: "task_template.yaml"
#counterparty settings
iteration_time: 30


# optional, sets counterparty for orders to take, must be HEX(40) string. Will be removed automatically in case of error/not set
counterparty: ""
# Identity level of the counterparty. Can be "anonymous", "registered", "identified" and "professional".
identity: "anonymous"

#node config

# MB, integers only
ramsize: 2000
# GB, integers only
storagesize: 1
#number of cores, integers only
cpucores: 1
sysbenchsingle: 500
sysbenchmulti: 1000
# Mbits, integers only
netdownload: 10
# Mbits, integers only
netupload: 10
# $ per hour
price: "0.05"

#network settings

# Indicates whether overlay networking is required, boolean only
overlay: false
# Indicates whether inbound connections are required and public IP should be present on worker, boolean only
incoming: false

#gpu config (optional). If not required, set gpucount: "0"

#number of units
gpucount: 1
# GPU unit RAM,MB, integers only
gpumem: 3000
# MH/s, integers only
ethhashrate: 0

