---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: monitor.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    http_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: http_monitor.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    monitor:
        level: DEBUG
        handlers: [console, info_file_handler]
        propagate: no
    monitor_http:
        level: DEBUG
        handlers: [http_file_handler]
        propagate: no